title: Nancy-Liège Workshops <br> on <br> Mathematical Intuition
logo: /assets/img/poincare.jpg
description: Two workshops organized in Nancy and Liège.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
